
  
CREATE TABLE IF NOT EXISTS     create table users (
       id int8 generated by default as identity,
        cpf varchar(255) not null,
        email varchar(255) not null,
        name varchar(255) not null,
        password varchar(255) not null,
        primary key (id)
    );