
  
CREATE TABLE   users (
       id int8 generated by default as identity,
        cpf varchar(255) not null,
        email varchar(255) not null,
        name varchar(255) not null,
        password varchar(255) not null,
        primary key (id)
    );
    
    
     
CREATE TABLE   wallet (
        id int8 generated by default as identity,
           name varchar(255) not null,
        value decimal(10, 2) not null,
        primary key (id)
    );
    
    
CREATE TABLE   users_wallet (
       id bigint generated by default as identity,
        users bigint,
        wallet bigint,
        primary key (id)
    );
    
    
    
    
    create table wallet_items (
       id int8 generated by default as identity,
        date timestamp not null,
        description varchar(255),
        type varchar(255) not null,
        value numeric(19, 2) not null,
        wallet int8 not null,
        primary key (id)
    );
    
    
    
    
    