
  
CREATE TABLE IF NOT EXISTS     users (
       id int8 generated by default as identity,
        cpf varchar(255) not null,
        email varchar(255) not null,
        name varchar(255) not null,
        password varchar(255) not null,
        primary key (id)
    );
    
    
     
CREATE TABLE IF NOT EXISTS  wallet (
        id int8 generated by default as identity,
           name varchar(255) not null,
        value decimal(10, 2) not null,
        primary key (id)
    );
    
    
CREATE TABLE IF NOT EXISTS users_wallet (
       id bigint generated by default as identity,
        users bigint,
        wallet bigint,
        primary key (id)
    )
    
    